from .code_execution import format_prompt_execution, format_prompt_execution_cot
from .code_generation import format_prompt_generation
from .test_output_prediction import format_prompt_test_output
from .self_repair import format_prompt_self_repair
